"""add_auth_user_roles_reset_tokens

Revision ID: e8f9ccd28d04
Revises: 1c921af888f7
Create Date: 2026-04-03 18:56:35.578785

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e8f9ccd28d04"
down_revision: str | Sequence[str] | None = "1c921af888f7"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.alter_column("email", existing_type=sa.VARCHAR(length=320), nullable=False)
        batch_op.create_unique_constraint("uq_users_email", ["email"])
        batch_op.create_unique_constraint("uq_users_phone_number", ["phone_number"])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_constraint("uq_users_phone_number", type_="unique")
        batch_op.drop_constraint("uq_users_email", type_="unique")
        batch_op.alter_column("email", existing_type=sa.VARCHAR(length=320), nullable=True)

    # ### end Alembic commands ###
